### ISSUE TITLE
new config, issues startin

### ISSUE THREAD

**Issue by mgaulton** [Lex-2008/facebook2email#1] opened 2023-03-20 01:53 UTC
Hey there, 
I'm really liking the look of your code, I need something like this for scraping a club facebook and posting to our website for group posts. I would appreciate any suggestions you could make to get this to work.

I installed and had issues getting vnc to connect, it won't accept connections.

I tried running without that step but get the below when trying the cron job 
 docker run --rm -v /opt/brgc/facebook2email:/data --shm-size=2g ultrafunk/undetected-chromedriver /data/script.py

`
running keepUpScreen()
sleeping
starting
opening
sleeping
working
working on 28 posts
Traceback (most recent call last):
  File "/data/script.py", line 54, in <module>
    post_urls = [x.attrs['href'].split('?')[0] for x in post_links if '/permalink/' in x.attrs['href']]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/script.py", line 54, in <listcomp>
    post_urls = [x.attrs['href'].split('?')[0] for x in post_links if '/permalink/' in x.attrs['href']]
                                                                                       ~~~~~~~^^^^^^^^
KeyError: 'href'
`

**Comment by Lex-2008** [comment] 2023-03-20 08:36
Hi!

vnc not conecting is strange. Are you running docker and vnc client on the same machine? Or docker on a remote instance (for example, on a VPS), and vnc client on your local machine?

Try checking if the port is open and reachable from the machine where you're running VNC client from. For example, using nmap: `nmap -p 5900 <remote-machine-ip>`: for me it properly shows port being "open" or "closed" depending of whether I have `x11vnc` running inside the container, or not.

This will help us understand on which side of network the issue is.

For the second issue - it looks like the post has links (`<a>` tags) without destination (`<a href>`)... That was unexpected. I've just pushed a fix / workaround to skip over links, but I wonder if there might be more surprises in Facebook HTML code. I'm using this script with only two groups, and I already saw that they have slightly different HTML code in non-mobile version. Please let me know if the fix helps!

**Comment by mgaulton** [comment] 2023-03-20 20:16
vmc in docker is on my linux host. I can see connection attempts from my client workstation, but it never connects.
I'll have to try again so I can get you the log lines
EDIT: both on my home networks. linux host, windows client.

Awesome, I've been fighting with the code all day, trying little tweaks! update you soon!

**Comment by mgaulton** [comment] 2023-03-21 04:03
ok, i started from scratch and seem to have it working but I'm encountering a small issue.
for my use case, I need each post to be a separate email, so I'm playing with that now!
thank you!

**Comment by mgaulton** [comment] 2023-03-21 19:34
Follow up question, how do I inject new modules into the image? pip install <module> doesn't work. 
I'm trying to write in some fuzzy date logic :)

**Comment by Lex-2008** [comment] 2023-03-22 11:10
hmm, i thought that I wrote something about sending each post to be a separate email, but guess my answer disappeared... Oh well, hope you figured it out :)

Regarding installing new modules - pip install works for me:
```
$ docker run --rm -it ultrafunk/undetected-chromedriver pip install python-gtmetrix2
running: pip install python-gtmetrix2
running keepUpScreen()
Collecting python-gtmetrix2
  Downloading python_gtmetrix2-0.3.1-py3-none-any.whl (13 kB)
Installing collected packages: python-gtmetrix2
Successfully installed python-gtmetrix2-0.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
```
Can you show me what doesn't work for you?

**Comment by mgaulton** [comment] 2023-03-22 13:47
It works but then the code can't find the module. I redo the install, and it reinstalls like it wasn't there.

**Comment by Lex-2008** [comment] 2023-03-23 10:51
Please show me what you do before I accuse you of not knowing how Docker works :)

You know that running `docker run --rm -it ultrafunk/undetected-chromedriver bash` creates a _temporary_ container - and **everything** what you do there **disappears** as soon as you close/quit/exit it, right?

**Comment by mgaulton** [comment] 2023-03-23 13:51
Now that I thought about it yes, I do. I'm used to only using persistent containers so ... imma plead idiot in this one.

**Comment by Lex-2008** [comment] 2023-03-23 20:20
I guess in other places it can be explained better, but basically when you run `docker run ...` - it creates a new _container_ with a copy[^1] of all files from the _image_. You work inside this container, and all changes you made to its filesystem disappear when you run `docker rm ...` (or when you quit container if it was started with `docker run --rm`). Hence why we use "volumes" - they are like "windows to outside world": directories from real filesystem mounted into the container. Hence, all changes to files in these directories which you do while container is running are preserved when the container is destroyed.

To achieve what you want, you just need to create a new _image_. To do this, simply create a file called `Dockerfile` inside an empty directory with a content like this:

````
FROM ultrafunk/undetected-chromedriver
RUN pip install python-gtmetrix2 && echo other bash commands
````

and run: `docker build -t my-chromedriver` while you're inside this directory.

After that, you will be able to use the image called "my-chromedriver" whenever you want instead of "ultrafunk/undetected-chromedriver". For example, like this:

````
docker run --rm -v /opt/brgc/facebook2email:/data --shm-size=2g my-chromedriver /data/script.py
````

Hope that helps!

[^1]: technically it's not a "copy" but _overlay_ of temporary (initially empty) filesystem over a read-only filesystem - this makes it faster and consume less space, but doesn't matter for this simple explanation.

**Closed as completed** 2023-03-26 18:18 UTC
